package com.moviejukebox.allocine;

import java.io.IOException;
import java.io.File;

import java.net.URL;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.JAXBException;
import javax.xml.stream.XMLEventReader;
import javax.xml.stream.XMLStreamException;

// import java content classes generated by binding compiler
import com.moviejukebox.allocine.jaxb.ObjectFactory;
import com.moviejukebox.allocine.MovieInfos;

public class XMLAllocineAPIHelper {

    private static final JAXBContext context = initContext();

    private static JAXBContext initContext() {
        try {
            return JAXBContext.newInstance("com.moviejukebox.allocine.jaxb");
        }
        catch (Exception error) {
            throw new RuntimeException("XMLAllocineAPIHelper: Got error during initialization", error);

        }
    }

    protected static Unmarshaller createAllocineUnmarshaller()  throws JAXBException {
        Unmarshaller unmarshaller = context.createUnmarshaller();
        // Use our own ObjectFactory so we can add behaviours in our classes
        unmarshaller.setProperty("com.sun.xml.bind.ObjectFactory", new ObjectFactory());
        return unmarshaller;
    }

    protected static MovieInfos validMovieElement(Object rootElement) {
        if (rootElement instanceof MovieInfos) {
            return (MovieInfos) rootElement;
        }
        // Error
        return null;
    }

    public static MovieInfos getMovieInfos(String AllocineId) throws IOException, JAXBException, XMLStreamException {
        URL url = new URL("http://api.allocine.fr/xml/movie?partner=3&profile=large&code=" + AllocineId);
        Unmarshaller unmarshaller = createAllocineUnmarshaller();
        return validMovieElement(unmarshaller.unmarshal(url));
    }

    public static MovieInfos getMovieInfos(File file) throws IOException, JAXBException {
        Unmarshaller unmarshaller = createAllocineUnmarshaller();
        return validMovieElement(unmarshaller.unmarshal(file));
    }
}
